### ISSUE TITLE
[feature request] in-expression

### ISSUE THREAD

**Issue by SkyyySi** [pigpigyyy/Yuescript#140] opened 2023-06-25 18:12 UTC
I think Python-like `in`-expressions would be a nice addition to allow for checking whether an object is in a table. It could be done like this:

```moonscript
mylist = { "foo", "bar", "biz", "baz" }

if "biz" in mylist
    print("Has biz")

has_bar = "bar" in mylist

print("has_bar = #{has_bar}")
```

which compiles to:

```lua
local mylist = {
    "foo",
    "bar",
    "biz",
    "baz"
}
if (function()
    local result
    result = false
    for k, v in pairs(mylist) do
        if v == "biz" then
            result = true
            break
        end
    end
    return result
end)() then
    print("Has biz")
end
local has_bar
do
    local result
    result = false
    for k, v in pairs(mylist) do
        if v == "bar" then
            result = true
            break
        end
    end
    has_bar = result
end
return print("has_bar = " .. tostring(has_bar))
```

**Comment by GokuHiki** [comment] 2023-06-28 09:23
Well... 'in' in python would make sense because python have 'dict' and 'list'.
```Python
print(1 in [1,2,3])
print("a" in {"a": 1})
```
But in lua/yue, 'in' can be very ambiguous. It is unclear to check key or value in table? is this table is 'list like' or 'dict like'? Should loop with 'pairs' or 'ipairs'?

Choice implements any option would lead to not satisfy for other cases!
And make thing more complicated, Yue already has support for 'in' constant table:
```moonscript
if "biz" in { "foo", "bar", "biz", "baz" }
  print 'found'
```
Thanks and regards!

**Comment by GokuHiki** [comment] 2023-06-29 05:03
Well... there are never has any edge cases like this in python, this example is simple don't exist because nobody code like this:
```python
mydict = {
    "foo": "bar"
}

class UndefinedField:
    pass

if mydict.get("biz", UndefinedField) is UndefinedField:
    # ...
```
but:
```
if "biz" in mydict:
  pass
```
It work in python because with dict 'in' check the key in keys, with list 'in' find value in values! That is common sense.

But lua is the language without common sense! 😓
lua can not compare to python [Beautiful, Explicit, Explicit] because in lua all we get is table. And Yue cannot escape it!

If yue has 'in'. What would it do?
  + find value in a table that act like list with 'ipairs' => make sense, but what about list with gaps?
  + find value in a table that act like dict with 'pairs' => make no sense, nobody that code like that!

I would like to have 'in' dynamic in Yue too. I have try with macro. But there I see some downside that I don't like and simple giveup on that idea:
  + Create and run anonymous, the big no no when I run lua in game.
  + Because I work a lot with python, sometime I make a mistake when work with table dict like and create the silent error that took a ton of time to debug!
  + It simple to make a function for that like all the lua coder code!

Yue have a lot of rich features, but add more features that not well consider can create more burden to maintain language for the author! I already happy with author focus maintain the language for now!

Thanks and regards!

**Comment by pigpigyyy** [comment] 2023-06-29 06:39
> compiles to... this mess
> 
> ```lua
> local has
> do
>     local _val_0 = "foo"
>     return {
>         [1] = "bar",
>         x = "foo"
>     } == _val_0
> end
> ```
Confirmed it is a bug and made a fix. This code should compile to:
```lua
local has
do
    local _val_0 = "foo"
    has = {
        [1] = "bar",
        x = "foo"
    } == _val_0
end
```
The expressions in the braces of `in { }` are just used for comparison.

**Comment by pigpigyyy** [comment] 2023-06-29 07:03
> ```moonscript
> mylist = { "foo", "bar", "biz", "baz" }
> 
> if "biz" in mylist
>     print("Has biz")
> 
> has_bar = "bar" in mylist
> 
> print("has_bar = #{has_bar}")
> ```
How about generating this code to:
```lua
local mylist = {
  "foo",
  "bar",
  "biz",
  "baz"
}
if (#mylist > 0 and (function()
  for i = 1, #mylist do
    if mylist[i] == "biz" then
      return true
    end
  end
  return false
end)() or mylist["biz"] ~= nil) then
  print("Has biz")
end
local has_bar
do
  local result = false
  for i = 1, #mylist do
    if mylist[i] == "biz" then
      result = true
      break
    end
  end
  if not result then
    result = mylist["biz"] ~= nil
  end
  has_bar = result
end
return print("has_bar = " .. tostring(has_bar))
```
If a table has only an array part, the `in` expression will match its elements by values. And if a table has only a hash part, the `in` expression will skip the array part then match hash part by key and tell if the paired value exists.
If a table has both an array part and a hash part, the `in` expression will first try matching the array part, if nothing matches, continue to do the hash part matching.

**Comment by GokuHiki** [comment] 2023-06-30 06:36
> ```moonscript
> has = "foo" in { [1]: "bar", x: "foo" }
> ```

How about change { } => [ ] make it more clear that: it not a 'lua table', but a 'yue constant list'!

```moonscript
has = "foo" in [ [1]: "bar", x: "foo" ]
```

**Comment by pigpigyyy** [comment] 2023-06-30 06:45
The brackets in `in-expression` are already used for representing closed intervals.
```moonscript
if num in [1, 10]
  print "number is in 1 to 10"
list = {1, 2, 3} -- is currently a valid list literal
```
Maybe we can throw an error, when the content in the `in-expression` is in a form of complex table literal instead of just a simple list.

**Comment by pigpigyyy** [comment] 2023-06-30 10:49
Had a second thought that the `in-expression` should not be used for table hash part existence checking. Because `tab[key]?` is already sufficient for this purpose. Adding similar functions to `in-expression` will lead to generating lots of redundant codes when you are just for hash part checking.  Tried adding the list table checking to Yuescript by commit 85a2da5cbbbbfb27f3b65ac67d083dd2443d223d.

**Closed** 2023-09-25 16:22 UTC
